
function init(self)
	msg.post(".", "acquire_input_focus")
	self.has_child = false
	self.child_id = nil
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("trigger_response") then
        if message.enter then
            -- take action for entry
            print("I am now inside", message.other_id)
			self.can_i_drag_it = true
			self.child_id = message.other_id
        else
            -- take action for exit
            print("I am now outside", message.other_id)
			self.can_i_drag_it = false
			self.child_id = nil
        end
    end
end

function on_input(self, action_id, action)
	self.pos = vmath.vector3(action.x, action.y, 0)
	go.set_position(self.pos)
	if action.pressed and self.can_i_drag_it == true and self.has_child == false then
		msg.post(self.child_id, "set_parent", { parent_id = go.get_id(), keep_world_transform = 1 })
		self.has_child = true
	elseif action.released and self.has_child == true then
		msg.post(self.child_id, "set_parent", { keep_world_transform = 1 })
		self.has_child = false
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
